### ISSUE TITLE
KV plugin with the On-Premise Windows VM

### ISSUE THREAD

**Issue by mogrodniczak** [microsoft/Azure-Key-Vault-Plugin-gMSA#4]
Hi,

I just wanted to ask. Is it possible to use this plugin along with the On-Premise Windows Virtual Machine?

It seems that On-Premise VM cannot be assigned to Azure Managed Identity.

Is there any other way to utilize this plugin with On-Premise?

**Comment by judyliu-ms** [comment]
Hi @mogrodniczak unfortunately there is not
